name: CI

on:
  push:
    branches: [ main, web-migration ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: python -m pip install -r apps/server/requirements.txt
      - run: pytest
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm --prefix packages/game-rules-ts install
      - run: npm --prefix packages/game-rules-ts test
      - run: npm --prefix apps/web install
      - run: npm --prefix apps/web test
